# Generated by Django 2.0.6 on 2019-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrption')),
                ('year', models.IntegerField(verbose_name='Relaese Year')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Movie Rating')),
                ('cast', models.TextField(blank=True, null=True, verbose_name='Cast')),
            ],
        ),
    ]
