# Generated by Django 2.0.6 on 2019-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20191114_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='Release Year'),
        ),
    ]
